language: python
python:
    - '3.8'

install:
    - pip install -r ./requirements.txt

env:
    - PYTHONPATH=/home/travis/build/alisha-bhatia/hotspot

script:
    - make tests

#deploy to heroku on push to master
deploy:
    - provider: heroku
      api_key: -iLsqBYfo7Bnb5I7V4JT2w
      app: hotspot
      on:
          branch: master
